[[promise-done]]
== Promise.prototype.done とは何か?

既存のPromise実装ライブラリを利用したことがある人は、
`then` の代わりに使う `done` というメソッドを見たことがあるかもしれません。

それらのライブラリでは `Promise.prototype.done` というような実装が存在し、
使い方は`then`と同じですが、promiseオブジェクトを返さないようになっています。

`Promise.prototype.done` は、<<es6-promises,ES6 Promises>>や<<promises-aplus,Promises/A+>>の仕様には
存在していない記述ですが、多くのライブラリが実装しています。

このセクションでは、`Promise.prototype.done`とは何か?
また何故このようなメソッドが多くのライブラリで実装されているかについて学んでいきましょう。

=== doneを使ったコード例

実際にdoneを使ったコードを見てみると`done`の挙動が分かりやすいと思います。

[source,js]
[[promise-done-example.js]]
.promise-done-example.js
----
include::embed/embed-promise-done-example.js[]
----

最初に述べたように、`Promise.prototype.done`は本来仕様にはないため、
利用する際は実装されているライブラリを使うか自分で実装する必要があります。

実装については後で解説しますが、まずは`then`を使った場合と`done`を使ったものを比較してみます。

比べて見ると以下のような違いがあることが分かります。

* `done` はpromiseオブジェクトを返さない
** つまり、doneの後に`catch`等のメソッドチェーンはできない
* `done` の中で発生したエラーはそのまま外に例外として投げられる
** つまり、Promiseによるエラーハンドリングが行われない

`done` はpromiseオブジェクトを返していないので、
Promise chainの最後に書くべきメソッドというのはわかると思います。

また、Promiseには強力なエラーハンドリング機能があると紹介していましたが、
`done` の中ではそのエラーハンドリングが行われていません。

何故このようなPromiseの機能とは相反するメソッドが、多くのライブラリで実装されいるかについては
次のようなPromiseの失敗例を見ていくと分かるかもしれません。

=== 沈黙したエラー

Promiseには強力なエラーハンドリング機能がありますが、
この機能がヒューマンエラーをより複雑なものにしてしまう一面があります。

つぎのような、promiseを返す関数を考えてみましょう。

[source,js]
[[json-promise.js]]
.json-promise.js
----
include::embed/embed-json-promise.js[]
----

渡された値を`JSON.parse`してpromiseオブジェクトを返す関数ですね。

